name: "CI"
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 0'  # runs weekly on Sunday at 00:00
    - cron: '0 0 25 * *' # runs on day-of-month 25 at 00:00

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v9
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}
          extra_nix_config: "experimental-features = nix-command flakes pipe-operators" 
      - uses: cachix/cachix-action@v15
        with:
          name: r17
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: pre-commit-hooks,nix-community
          skipPush: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push' && matrix.os == 'macos-latest') }}

      - uses: DeterminateSystems/update-flake-lock@v24
        name: Update flake.lock
        if: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.event.schedule == '0 0 25 * *' }}
        with:
          token: ${{ secrets.GH_TOKEN }}
          inputs: nixpkgs-master nixpkgs-stable nixpkgs-unstable nix nix-darwin flake-parts home-manager pre-commit-hooks
          branch: monthly-lock
          git-author-name: 'anakmangang'
          git-author-email: 'contact@evilfactorylabs.org'
          git-committer-name: 'anakmangang'
          git-committer-email: 'contact@evilfactorylabs.org'
          commit-msg: 'chore(lockfile): update flake.lock'
          pr-title: 'chore(lockfile): update flake.lock'
          pr-labels: |
            dependencies
            automated
            monthly

      - uses: DeterminateSystems/update-flake-lock@v24
        name: Update flake.lock
        if: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.event.schedule == '0 0 * * 0' }}
        with:
          token: ${{ secrets.GH_TOKEN }}
          inputs: nixvim nixpkgs-fmt neorg-overlay home-manager nix-env ts-rescript vimPlugins_vim-rescript vimPlugins_supermaven-nvim
          branch: weekly-lock
          git-author-name: 'anakmangang'
          git-author-email: 'contact@evilfactorylabs.org'
          git-committer-name: 'anakmangang'
          git-committer-email: 'contact@evilfactorylabs.org'
          commit-msg: 'chore(lockfile): update flake.lock'
          pr-title: 'chore(lockfile): update flake.lock'
          pr-labels: |
            dependencies
            automated
            weekly

      - run: nix flake show .
      - run: nix build .#nvim
      - run: nix build ".#darwinConfigurations.$HOSTNAME.system"
        env: 
          HOSTNAME: "eR17"
